[colors.primary]
foreground = "#3c3836"
background = "#faf7f0"
dim_foreground = "#7c6f64"
bright_foreground = "#282828"

[colors.cursor]
text = "#faf7f0"
cursor = "#cc241d"

[colors.vi_mode_cursor]
text = "#faf7f0"
cursor = "#cc241d"

[colors.search.matches]
foreground = "#282828"
background = "#f2e5bc"

[colors.search.focused_match]
foreground = "#faf7f0"
background = "#cc241d"

[colors.hints.start]
foreground = "#458588"
background = "#f5f0e8"

[colors.hints.end]
foreground = "#689d6a"
background = "#f5f0e8"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#3c3836"
background = "#f5f0e8"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#32302f"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#7c6f64"

